# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: schoukou <schoukou@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/20 14:08:55 by afaris            #+#    #+#              #
#    Updated: 2022/10/26 20:53:08 by schoukou         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CC = gcc

CFLAGS = -Wall -Wextra -Werror

SRC = ft_atoi.c ft_strtrim.c ft_strlen.c ft_strjoin.c \
ft_bzero.c ft_memcpy.c ft_memchr.c \
ft_isalnum.c ft_isascii.c ft_isprint.c \
ft_toupper.c ft_tolower.c ft_isdigit.c \
ft_isalpha.c ft_strdup.c ft_strchr.c \
ft_substr.c ft_strrchr.c ft_calloc.c \
ft_strncmp.c ft_memcmp.c ft_strlcpy.c \
ft_memset.c ft_strlcat.c ft_strnstr.c \
ft_strmapi.c ft_putchar_fd.c ft_putstr_fd.c \
ft_putendl_fd.c ft_split.c ft_putnbr_fd.c \
ft_itoa.c ft_striteri.c ft_memmove.c \
ft_strjoinx.c

BONUSSRC = ft_lstnew.c ft_lstadd_front.c  \
ft_lstsize.c ft_lstlast.c ft_lstadd_back.c \
ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c

BONUSOBJ = ${BONUSSRC:.c=.o}
OBJ = ${SRC:.c=.o}

all: $(NAME)

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@
	ar crs $(NAME) $@

$(NAME): $(OBJ)

bonus: $(BONUSOBJ)

clean :
	rm -f ${BONUSOBJ} ${OBJ}

fclean : clean
	rm -f $(NAME)

re : fclean all

.PHONY: re fclean all clean bonus